#!/bin/bash
# chkconfig:   - 25 75
# description: carbon-cache
# processname: carbon-cache

export PYTHONPATH="$GRAPHITE_DIR/lib:$PYTHONPATH"

# Source function library.
if [ -e /etc/rc.d/init.d/functions ]; then
    . /etc/rc.d/init.d/functions;
fi;


CARBON_DAEMON="cache"
CONF_DIR="/etc/carbon"

function die {
  echo $1
  exit 1
}

start(){
    for CONF_FILE in $(ls ${CONF_DIR}/*.conf);do
    	INSTANCE=`grep "^\[${CARBON_DAEMON}:c" ${CONF_FILE} | cut -d \[ -f 2 | cut -d \] -f 1 | cut -d : -f 2`
        if [ "X${INSTANCE}" == "X" ]; then
            continue
        fi
        echo "Starting carbon-${CARBON_DAEMON}:${INSTANCE}..."
        /bin/carbon-${CARBON_DAEMON} --instance=${INSTANCE} --conf=${CONF_DIR}/${INSTANCE}.conf start;
        if [ $? -eq 0 ]; then
            echo_success
        else
            echo_failure
        fi;
        echo ""
    done;
}

stop(){
    for CONF_FILE in $(ls ${CONF_DIR}/*.conf);do
    	INSTANCE=`grep "^\[${CARBON_DAEMON}:c" ${CONF_FILE} | cut -d \[ -f 2 | cut -d \] -f 1 | cut -d : -f 2`
        if [ "X${INSTANCE}" == "X" ]; then
            continue
        fi
        echo "Stoping carbon-${CARBON_DAEMON}:${INSTANCE}..."
        /bin/carbon-${CARBON_DAEMON} --instance=${INSTANCE} --conf=${CONF_DIR}/${INSTANCE}.conf stop;

        if [ `sleep 3; /usr/bin/pgrep -f "carbon-${CARBON_DAEMON} --instance=${INSTANCE}" | /usr/bin/wc -l` -gt 0 ]; then
            echo "Carbon did not stop yet. Sleeping longer, then force killing it...";
            sleep 20;
            /usr/bin/pkill -9 -f "carbon-${CARBON_DAEMON} --instance=${INSTANCE}";
        fi;

        if [ $? -eq 0 ]; then
            echo_success
        else
            echo_failure
        fi;
        echo ""
    done;
}

status(){
    for CONF_FILE in $(ls ${CONF_DIR}/*.conf);do
    	INSTANCE=`grep "^\[${CARBON_DAEMON}:c" ${CONF_FILE} | cut -d \[ -f 2 | cut -d \] -f 1 | cut -d : -f 2`
        if [ "X${INSTANCE}" == "X" ]; then
            continue
        fi
        /bin/carbon-${CARBON_DAEMON} --instance=${INSTANCE} --conf=${CONF_DIR}/${INSTANCE}.conf status;
        if [ $? -eq 0 ]; then
            echo_success
        else
            echo_failure
        fi;
        echo ""
    done;
}

case "$1" in
  start)
    start 
    ;;
  stop)
    stop
    ;;
  status)
    status
    ;;
  restart|reload)
    stop
    start
    ;;
  *)
    echo $"Usage: $0 {start|stop|restart|status}"
    exit 1
esac

